import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
// import { cn } from "@/lib/utils";
import Header from "@/components/custom/header";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap", // optional, improves performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className}
          min-h-screen bg-background font-manrope antialiased
        `}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
